export const SET_APP = "SET_APP";
export const SET_SYNC = "SET_SYNC";
export const SET_MENU = "SET_MENU";
export const SET_TABLES = "SET_TABLES";
export const START_TICK = "START_TICK";
export const SET_CONFIG = "SET_CONFIG";
export const SET_DEVICE = "SET_DEVICE";
export const PHONE_RING = "PHONE_RING";
export const ADD_SPOOLER = "ADD_SPOOLER";
export const SET_REQUEST = "SET_REQUEST";
export const SET_STATION = "SET_STATION";
export const SET_CATEGORY = "SET_CATEGORY";
export const SET_LAYOUTS = "SET_LAYOUTS";

export const REMOVE_TABLE = "REMOVE_TABLE";
export const UPSERT_INVOICE = "UPSERT_INVOICE";
export const SET_TEMPLATES = "SET_TEMPLATES";
export const NEW_PHONE_CALL = "NEW_PHONE_CALL";
export const SET_TODAY_ORDER = "SET_TODAY_ORDER";
export const REMOVE_SPOOLER = "REMOVE_SPOOLER";
export const CREATE_ORDER_INSTANCE = "CREATE_ORDER_INSTANCE";
export const ARCHIVE_ORDER = "ARCHIVE_ORDER";

export const SET_BOOKS = "SET_BOOKS";
export const UPDATE_MENU_ITEM = "UPDATE_MENU_ITEM";
export const REMOVE_MENU_ITEM = "REMOVE_MENU_ITEM";
export const REMOVE_REQUEST_ITEM = "REMOVE_REQUEST_ITEM";
export const UPDATE_REQUEST_ITEM = "UPDATE_REQUEST_ITEM";
export const UPDATE_TABLE_SECTION = "UPDATE_TABLE_SECTION";
export const UPDATE_MENU_CATEGORY = "UPDATE_MENU_CATEGORY";
export const UPDATE_REQUEST_ACTION = "UPDATE_REQUEST_ACTION";
export const UPDATE_REQUEST_CATEGORY = "UPDATE_REQUEST_CATEGORY";
export const REFRESH_CURRENT_ORDER = "REFRESH_CURRENT_ORDER";
export const EMPTY_ARCHIVE_ORDER = "EMPTY_ARCHIVE_ORDER";

export const SET_OPERATOR = "SET_OPERATOR";
export const SET_TICKET = "SET_TICKET";
export const RESET_ORDER = "RESET_ORDER";
export const SET_CUSTOMER = "SET_CUSTOMER";
export const SET_FAVORITES = "SET_FAVORITES";
export const RESET_CUSTOMER = "RESET_CUSTOMER";

export const SET_ORDER = "SET_ORDER";
export const SET_SIDES = "SET_SIDES";
export const SET_POINTER = "SET_POINTER";
export const RESET_POINTER = "RESET_POINTER";
export const ADD_TO_ORDER = "ADD_TO_ORDER";
export const PUSH_TO_ORDER = "PUSH_TO_ORDER";
export const ALTER_ITEM = "ALTER_ITEM";
export const UPDATE_TABLE = "UPDATE_TABLE";

export const SET_QTY = "SET_QTY";
export const LESS_QTY = "LESS_QTY";
export const MORE_QTY = "MORE_QTY";
export const SPLIT_ITEM = "SPLIT_ITEM";
export const SET_CHOICE_SET = "SET_CHOICE_SET";
export const ALERT_CHOICE_SET = "ALERT_CHOICE_SET";
export const ALTER_ITEM_OPTION = "ALTER_ITEM_OPTION";
export const SET_PRICE_FOR_CHOICE_SET = "SET_PRICE_FOR_CHOICE_SET";
export const SET_CHOICE_SET_TARGET = "SET_CHOICE_SET_TARGET";
export const EMPTY_CHOICE_SET = "EMPTY_CHOICE_SET";
export const RESET_CHOICE_SET = "RESET_CHOICE_SET";
export const RESET_TABLE = "RESET_TABLE";
export const SET_VIEW_TABLE = "SET_VIEW_TABLE";
export const SET_VIEW_ORDER = "SET_VIEW_ORDER";
export const RESET_VIEW_TABLE = "RESET_VIEW_TABLE";

export const EMPTY_CUSTOMER_INFO = "EMPTY_CUSTOMER_INFO";
